AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  INDEX:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.index
      Runtime: python3.6
      CodeUri: .
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: get
  ASD:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.asd
      Runtime: python3.6
      CodeUri: .
      Events:
        Post:
          Type: Api
          Properties:
            Path: /asd
            Method: get
